/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisJob {
  'id' : string,
  'status' : string,
  'name' : string,
  'size' : bigint,
  'fileType' : string,
  'uploadedAt' : bigint,
}
export interface AnalysisResult {
  'mediumCount' : bigint,
  'overallScore' : bigint,
  'isMalicious' : boolean,
  'threatScore' : bigint,
  'jobId' : string,
  'highCount' : bigint,
  'vulnerabilitiesCount' : bigint,
  'permissionsCount' : bigint,
  'lowCount' : bigint,
  'criticalCount' : bigint,
}
export interface _SERVICE {
  'deleteJob' : ActorMethod<[string], boolean>,
  'getAnalysisResults' : ActorMethod<[string], [] | [AnalysisResult]>,
  'listJobs' : ActorMethod<[], Array<AnalysisJob>>,
  'uploadFile' : ActorMethod<[string, string, bigint], AnalysisJob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];