/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisResult = IDL.Record({
  'mediumCount' : IDL.Nat,
  'overallScore' : IDL.Nat,
  'isMalicious' : IDL.Bool,
  'threatScore' : IDL.Nat,
  'jobId' : IDL.Text,
  'highCount' : IDL.Nat,
  'vulnerabilitiesCount' : IDL.Nat,
  'permissionsCount' : IDL.Nat,
  'lowCount' : IDL.Nat,
  'criticalCount' : IDL.Nat,
});
export const AnalysisJob = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'fileType' : IDL.Text,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteJob' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAnalysisResults' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AnalysisResult)],
      ['query'],
    ),
  'listJobs' : IDL.Func([], [IDL.Vec(AnalysisJob)], ['query']),
  'uploadFile' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [AnalysisJob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisResult = IDL.Record({
    'mediumCount' : IDL.Nat,
    'overallScore' : IDL.Nat,
    'isMalicious' : IDL.Bool,
    'threatScore' : IDL.Nat,
    'jobId' : IDL.Text,
    'highCount' : IDL.Nat,
    'vulnerabilitiesCount' : IDL.Nat,
    'permissionsCount' : IDL.Nat,
    'lowCount' : IDL.Nat,
    'criticalCount' : IDL.Nat,
  });
  const AnalysisJob = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'fileType' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteJob' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAnalysisResults' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AnalysisResult)],
        ['query'],
      ),
    'listJobs' : IDL.Func([], [IDL.Vec(AnalysisJob)], ['query']),
    'uploadFile' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [AnalysisJob], []),
  });
};

export const init = ({ IDL }) => { return []; };